version: '3.3'

services:
  db: # nome do container de mysql
    image: mysql:5.7 # especificando a imagem + versão
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: wordpress
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: helena
    #   MYSQL_PASSWORD: secret

  wordpress:
    depends_on: # depende de outro servico para funcionar
      - db
    image: wordpress:latest
    ports: 
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    # environment:
    #   WORDPRESS_DB_HOST: 3306
    #   WORDPRESS_DB_USER: helena
    #   WORDPRESS_DB_PASSWORD: secret
    #   WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}